name: Auto Login Angel One

on:
  schedule:
    - cron: '*/5 * * * *'  # runs every 5 minutes
  workflow_dispatch:  # lets you run manually

jobs:
  login:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      API_KEY: ${{ secrets.API_KEY }}
      TOTP_SECRET: ${{ secrets.TOTP_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
  run: pip install -r requirements.txt

      - name: Show installed packages
  run: pip list



      - name: Run auto_login script
        run: python auto_login.py
